export type ItemType =
    | BaseType
    | Beast
    | ClusterJewel
    | DeliriumOrb
    | DivinationCard
    | Essence
    | Fossil
    | HelmetEnchant
    | Incubator
    | Invitation
    | Map
    | Oil
    | Prophecy
    | Resonator
    | Scarab
    | SkillGem
    | UniqueAccessory
    | UniqueArmour
    | UniqueFlask
    | UniqueJewel
    | UniqueMap
    | UniqueWeapon
    | Vial
    | Watchstone;
